name: Build and package electron application

on: [push, pull_request]

jobs:
  run-tests:
    name: "Build and package electron application"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install environment
      run: npm install
    - name: build production code
      run: npm run build
    - name: package application
      run: npm run package
      env:
        CI: true
